import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import './style.css';

const viewport = document.querySelector('#viewport'), telemetry = document.querySelector('#telemetry');
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x9fc4d8); scene.fog = new THREE.Fog(0x9fc4d8, 420, 980);
const camera = new THREE.PerspectiveCamera(48, innerWidth / innerHeight, .1, 2000); camera.position.set(420, 360, 360);
const renderer = new THREE.WebGLRenderer({antialias: true, powerPreference: 'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio, 1.25)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; renderer.shadowMap.autoUpdate = false; renderer.shadowMap.needsUpdate = true; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.25; viewport.appendChild(renderer.domElement);
const qualityProfiles = {low:{pixelRatio:1.0, shadows:false, trail:18, links:80, effects:false}, medium:{pixelRatio:1.15, shadows:true, trail:35, links:180, effects:false}, high:{pixelRatio:1.5, shadows:true, trail:70, links:500, effects:true}};
let qualityName = 'auto', quality = qualityProfiles.medium, playbackSpeed = 1, renderFrame = 0;
function setQuality(name) { qualityName = name; const selected = name === 'auto' ? (!navigator.deviceMemory || navigator.deviceMemory <= 8 ? 'low' : 'medium') : name; quality = qualityProfiles[selected]; renderer.setPixelRatio(Math.min(devicePixelRatio, quality.pixelRatio)); renderer.shadowMap.enabled = quality.shadows; renderer.shadowMap.needsUpdate = true; document.querySelector('#quality').value = name; }
const controls = new OrbitControls(camera, renderer.domElement); controls.target.set(500, 35, 500); controls.enableDamping = true; controls.minPolarAngle = 0.18; controls.maxPolarAngle = Math.PI / 2 - 0.04; controls.minDistance = 80; controls.maxDistance = 1800;
scene.add(new THREE.HemisphereLight(0xd9efff, 0x5d654f, 3.8)); scene.add(new THREE.AmbientLight(0x9bb0bd, 1.2)); const sun = new THREE.DirectionalLight(0xffe4bd, 2.5); sun.position.set(220, 520, 140); sun.castShadow = true; sun.shadow.mapSize.set(2048,2048); scene.add(sun);
const world = new THREE.Group(); scene.add(world); const entities = new Map(), trails = new Map(), altitudeLines = new Map(), roleRings = new Map(), poiEntities = new Map(), footprintEntities = new Map(); const linkLayer = new THREE.Group(), taskLayer = new THREE.Group(), terrainLayer = new THREE.Group(); world.add(linkLayer, taskLayer, terrainLayer); const loadedTiles = new Map(); let replay = null, frame = 0, playing = false, terrainManifest = null, terrainHeightmap = null, sceneArena = 1000, sceneGcs = [-75, 500, 20], gcsMarker = null;
const roleColor = {SURVEY: 0x39d98a, RELAY: 0x45aaf2, BACKBONE: 0x00d5ff, RECOVER: 0xffb547, RETURN: 0xff6b6b, CHARGE: 0xc084fc, LAND: 0x76869a, STANDBY: 0xaab4c3};
function terrain() { const n=qualityName==='high'?120:80, half=sceneArena/2, geo=new THREE.PlaneGeometry(sceneArena,sceneArena,n,n); const pos=geo.attributes.position, colors=[]; const low=new THREE.Color(0x263f2b), grass=new THREE.Color(0x58764a), dry=new THREE.Color(0x9b8955), high=new THREE.Color(0x8d8b78); for(let i=0;i<pos.count;i++){const x=pos.getX(i)+half,z=pos.getY(i)+half; const broad=13*Math.sin(x/180)*Math.cos(z/230), ridge=6*Math.sin((x+z)/62)+3*Math.cos(z/38), river=-10*Math.exp(-((z-half-84*Math.sin(x/150))**2)/3600); const h=8+broad+ridge+river;pos.setZ(i,h);const moisture=Math.max(0,1-Math.abs(z-half-84*Math.sin(x/150))/170);let c=h>22?high.clone():h>13?grass.clone():dry.clone();c.lerp(low,Math.max(0,(8-h)/18));c.lerp(new THREE.Color(0x315d46),moisture*.35);colors.push(c.r,c.g,c.b);} geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals(); const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.96,metalness:0})); mesh.name='procedural-terrain'; mesh.rotation.x=-Math.PI/2; mesh.receiveShadow=true; mesh.position.set(half,0,half); world.add(mesh); const river=new THREE.Mesh(new THREE.PlaneGeometry(sceneArena,36),new THREE.MeshStandardMaterial({color:0x3d7890,roughness:.18,metalness:.15,transparent:true,opacity:.8}));river.rotation.x=-Math.PI/2;river.rotation.z=-.08;river.position.set(half,heightAt(half,half)+1.8,half);world.add(river); for(let i=0;i<(qualityName==='low'?24:60);i++){const x=20+(i*71)%(sceneArena-40),z=25+(i*113)%(sceneArena-50);const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(2+(i%4),0),new THREE.MeshStandardMaterial({color:i%2?0x6a6a5d:0x4e514d,roughness:1}));rock.position.set(x,heightAt(x,z)+2+(i%3)*.5,z);rock.scale.y=.6;rock.castShadow=quality.shadows;world.add(rock);} }
function drone(id){const g=new THREE.Group();g.scale.setScalar(1.18);const carbon=new THREE.MeshStandardMaterial({color:0x202a35,metalness:.72,roughness:.28});const dark=new THREE.MeshStandardMaterial({color:0x0d141c,metalness:.55,roughness:.3});const body=new THREE.Mesh(new THREE.CylinderGeometry(3.15,2.55,1.45,12),carbon);body.castShadow=quality.shadows;g.add(body);const canopy=new THREE.Mesh(new THREE.SphereGeometry(2.25,12,8),new THREE.MeshStandardMaterial({color:0x384d5c,metalness:.35,roughness:.22,transparent:true,opacity:.9}));canopy.scale.set(1,.42,.82);canopy.position.y=.72;g.add(canopy);const payload=new THREE.Mesh(new THREE.CylinderGeometry(1.15,1.35,1.5,10),dark);payload.position.y=-1.35;g.add(payload);const lens=new THREE.Mesh(new THREE.SphereGeometry(.72,12,8),new THREE.MeshStandardMaterial({color:0x07131b,metalness:.8,roughness:.12,emissive:0x071a24}));lens.position.set(0,-2.05,0);g.add(lens);const gimbal=new THREE.Mesh(new THREE.TorusGeometry(1.05,.12,6,16),new THREE.MeshStandardMaterial({color:0x687883,metalness:.7,roughness:.25}));gimbal.rotation.x=Math.PI/2;gimbal.position.y=-1.8;g.add(gimbal);const skidMat=new THREE.MeshStandardMaterial({color:0x26313b,metalness:.65,roughness:.35});for(const x of [-2.7,2.7]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.22,2.1,.22),skidMat);leg.position.set(x/1.6,-1.5,0);leg.rotation.z=x<0?-.18:.18;g.add(leg);const skid=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,5.8,8),skidMat);skid.rotation.z=Math.PI/2;skid.position.set(x/1.6,-2.45,0);g.add(skid);}const rotors=[];for(let i=0;i<6;i++){const a=i*Math.PI/3,x=Math.cos(a)*5.3,z=Math.sin(a)*5.3;const arm=new THREE.Mesh(new THREE.BoxGeometry(5.5,.3,.36),carbon);arm.position.set(x/2,0,z/2);arm.rotation.y=-a;g.add(arm);const motor=new THREE.Mesh(new THREE.CylinderGeometry(.72,.62,.8,10),dark);motor.position.set(x,0,z);g.add(motor);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.95,8),new THREE.MeshStandardMaterial({color:0x8d9aa3,metalness:.8,roughness:.2}));hub.position.set(x,.35,z);g.add(hub);const rotor=new THREE.Mesh(new THREE.CylinderGeometry(2.05,.08,.08,18),new THREE.MeshStandardMaterial({color:0xc5e5f2,transparent:true,opacity:.34,side:THREE.DoubleSide}));rotor.position.set(x,.48,z);g.add(rotor);rotors.push(rotor);}const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.08,.08,2.5,6),new THREE.MeshStandardMaterial({color:0x161d25,metalness:.5}));antenna.position.set(0,1.8,0);g.add(antenna);const ledL=new THREE.PointLight(0x39d98a,1.8,14),ledR=new THREE.PointLight(0xff4d5d,1.8,14);ledL.position.set(-2.2,.3,0);ledR.position.set(2.2,.3,0);g.add(ledL,ledR);g.userData={id,rotors,ledL,ledR};world.add(g);entities.set(id,g);const line=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xaab4c3,transparent:true,opacity:.6}));world.add(line);trails.set(id,line);return g; }
function heightAt(x,z){if(!terrainHeightmap)return 0;const grid=terrainHeightmap.grid, arena=terrainHeightmap.arena_m||500;const fx=Math.max(0,Math.min(grid-1,x/arena*(grid-1))),fz=Math.max(0,Math.min(grid-1,z/arena*(grid-1)));const x0=Math.floor(fx),z0=Math.floor(fz),x1=Math.min(x0+1,grid-1),z1=Math.min(z0+1,grid-1),tx=fx-x0,tz=fz-z0,e=terrainHeightmap.elevation_m;return (1-tz)*((1-tx)*e[z0][x0]+tx*e[z0][x1])+tz*((1-tx)*e[z1][x0]+tx*e[z1][x1]);}
function obstacle(o){const [x,z]=o.center_m,[sx,sz,sy]=o.size_m;const root=new THREE.Group();root.name=o.id;root.position.set(x,heightAt(x,z),z);const mat=(color,roughness=1,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});const add=(mesh,y=0)=>{mesh.position.y=y;mesh.castShadow=true;mesh.receiveShadow=true;root.add(mesh);return mesh;};if(o.kind==='building'){add(new THREE.Mesh(new THREE.BoxGeometry(sx,sz,sy),mat(0x8f918d,.9)),sz/2);const roof=add(new THREE.Mesh(new THREE.BoxGeometry(sx+4,2.2,sy+4),mat(0x4c5354,.92)),sz+1.1);roof.position.x=1;const windowMat=mat(0x163442,.22,.38);const rows=sz>25?2:1;const cols=Math.max(2,Math.floor(sx/16));for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const wx=(col-(cols-1)/2)*(sx*.72/Math.max(1,cols-1));const w=new THREE.Mesh(new THREE.BoxGeometry(Math.min(7,sx*.12),4.5,.16),windowMat);w.position.set(wx,7+row*10,-sy/2-.12);w.castShadow=false;root.add(w);}const door=new THREE.Mesh(new THREE.BoxGeometry(4.5,8,.2),mat(0x263238,.45,.1));door.position.set(-sx*.24,4,-sy/2-.16);door.castShadow=false;root.add(door);for(let i=0;i<2;i++){const unit=add(new THREE.Mesh(new THREE.BoxGeometry(7,1.4,4),mat(0x697273,.7,.2)),sz+2.1);unit.position.x=(i-.5)*14;}}else if(o.kind==='tower'){const steel=mat(0x68777c,.5,.65);for(const [lx,lz] of [[-1,-1],[-1,1],[1,-1],[1,1]]){const leg=add(new THREE.Mesh(new THREE.CylinderGeometry(.36,.5,sz,6),steel),sz/2);leg.position.x=lx*sx*.3;leg.position.z=lz*sy*.3;}for(const level of [sz*.25,sz*.5,sz*.75]){const deck=add(new THREE.Mesh(new THREE.BoxGeometry(sx*1.1,.45,sy*1.1),steel),level);deck.material=steel;}const mast=add(new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,8,6),steel),sz+4);const beacon=new THREE.Mesh(new THREE.SphereGeometry(1.1,8,6),new THREE.MeshBasicMaterial({color:0xff4d5d}));beacon.position.y=sz+8;root.add(beacon);}else if(o.kind==='bridge'){add(new THREE.Mesh(new THREE.BoxGeometry(sx,sz,sy),mat(0x59676b,.82)),sz/2);for(const side of [-1,1]){const rail=add(new THREE.Mesh(new THREE.BoxGeometry(sx,.8,.8),mat(0xa4b0b2,.55,.25)),sz+4);rail.position.z=side*(sy/2-.8);}}else{const rubbleMat=mat(0x766657,1);for(let i=0;i<8;i++){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(2.5+(i%3)*1.5,0),rubbleMat);rock.position.set((i*17)%Math.max(8,sx)-sx/2,1.5+(i%3)*1.8,(i*11)%Math.max(8,sy)-sy/2);rock.scale.y=.7;rock.castShadow=true;root.add(rock);}}world.add(root);}
function sceneDetails(){
  const roadMat=new THREE.MeshStandardMaterial({color:0x252b2d,roughness:1});
  for(const [x,z,rot] of [[250,250,0],[250,120,Math.PI/2],[120,350,0]]){const road=new THREE.Mesh(new THREE.PlaneGeometry(500,7),roadMat);road.rotation.x=-Math.PI/2;road.rotation.z=rot;road.position.set(x,heightAt(x,z)+.4,z);world.add(road);}
  const trunk=new THREE.CylinderGeometry(.8,.55,8,6), crown=new THREE.ConeGeometry(4,10,7);
  for(let i=0;i<34;i++){const x=18+(i*83)%465,z=18+(i*137)%465;if(x>180&&x<285&&z>220&&z<305)continue;const tree=new THREE.Group();const t=new THREE.Mesh(trunk,new THREE.MeshStandardMaterial({color:0x5a3927}));t.position.y=4;const c=new THREE.Mesh(crown,new THREE.MeshStandardMaterial({color:i%3?0x2e633f:0x3d7d4a}));c.position.y=11;tree.add(t,c);tree.position.set(x,heightAt(x,z),z);tree.scale.setScalar(.7+(i%4)*.12);tree.traverse(n=>n.castShadow=true);world.add(tree);}
}
function prepareTerrainAsset(object){object.traverse(x=>{if(x.isMesh){x.castShadow=quality.shadows;x.receiveShadow=true;if(x.material){x.material.side=THREE.FrontSide;x.material.roughness=.82;if(x.material.color)x.material.color.multiplyScalar(1.15);}}});}
function tileLod(){return quality===qualityProfiles.high?'high':quality===qualityProfiles.medium?'medium':'low';}
function unloadTile(id){const entry=loadedTiles.get(id);if(!entry)return;terrainLayer.remove(entry.object);entry.object.traverse(x=>{if(x.geometry)x.geometry.dispose();if(x.material){if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material.dispose();}});loadedTiles.delete(id);}
function updateTerrainTiles(){if(!terrainManifest?.tiles)return;const target=controls.target;const radius=quality===qualityProfiles.high?260:quality===qualityProfiles.medium?190:145;const lod=tileLod();const wanted=new Set();for(const tile of terrainManifest.tiles){const [x0,z0,x1,z1]=tile.bounds_m;const cx=(x0+x1)/2,cz=(z0+z1)/2;if(Math.hypot(cx-target.x,cz-target.z)<=radius+90){wanted.add(tile.id);if(!loadedTiles.has(tile.id)){const url=tile.lod_urls[lod];new GLTFLoader().load(url,g=>{prepareTerrainAsset(g.scene);g.scene.userData.tileId=tile.id;terrainLayer.add(g.scene);loadedTiles.set(tile.id,{object:g.scene,lod});const fallback=world.getObjectByName('procedural-terrain');if(fallback)fallback.visible=false;},undefined,()=>{});}}}for(const id of loadedTiles.keys())if(!wanted.has(id))unloadTile(id);}
function initializeScene(){terrain(); sceneDetails(); fetch('/scene/obstacles.json').then(r=>r.json()).then(d=>d.obstacles.forEach(obstacle)).catch(()=>{}); const useTiled=new URLSearchParams(location.search).get('tiles')==='1';const manifestUrl=useTiled?'/scene/scene_manifest_tiled.json':'/scene/scene_manifest.json';fetch(manifestUrl).then(r=>r.json()).then(m=>{terrainManifest=useTiled?m:null;if(m.tiles)updateTerrainTiles();if(m.fallback?.gltf_url){new GLTFLoader().load(m.fallback.gltf_url,g=>{const fallback=g.scene;fallback.name='real-terrain-fallback';prepareTerrainAsset(fallback);world.add(fallback);fallback.visible=!m.tiles;},undefined,()=>{});}if(m.terrain?.gltf_url){new GLTFLoader().load(m.terrain.gltf_url,g=>{prepareTerrainAsset(g.scene);if(m.terrain.albedo_url){new THREE.TextureLoader().load(m.terrain.albedo_url,tex=>{tex.colorSpace=THREE.SRGBColorSpace;g.scene.traverse(x=>{if(x.isMesh&&x.material){x.material.map=tex;x.material.needsUpdate=true;}});});}world.add(g.scene);const fallback=world.getObjectByName('procedural-terrain');if(fallback)fallback.visible=false;},undefined,()=>{});}document.title=`UAV-X · ${m.scene_id||'real scene'}`;}).catch(()=>{}); const gcs=new THREE.Mesh(new THREE.CylinderGeometry(8,10,3,24),new THREE.MeshStandardMaterial({color:0x45aaf2})); gcs.position.set(40,heightAt(40,40)+20,40); world.add(gcs);}
function loadScene(){fetch('/scene/terrain_heightmap.json').then(r=>r.json()).then(data=>{terrainHeightmap=data;initializeScene();}).catch(()=>initializeScene());}
function parse(text){const lines=text.trim().split(/\r?\n/); if(lines.length && lines[0].startsWith('{') && !text.trim().startsWith('{"schema_version":"uav-x-log')){try{return JSON.parse(text);}catch{}} const records=lines.map(x=>JSON.parse(x)); return {ticks:records.filter(x=>x.record_type==='tick'),events:records.filter(x=>x.record_type==='event'),manifest:records.find(x=>x.record_type==='manifest')||{},summary:records.find(x=>x.record_type==='summary')||{}};}
function poiMarker(p){const g=new THREE.Group();const priority=p.priority===1;const pin=new THREE.Mesh(new THREE.ConeGeometry(priority?3.2:2.5,7,6),new THREE.MeshStandardMaterial({color:priority?0xff4d6d:0xffb547,emissive:priority?0x5a0015:0x5a2d00}));pin.position.y=3;g.add(pin);const ring=new THREE.Mesh(new THREE.TorusGeometry(priority?7:5,.35,8,24),new THREE.MeshBasicMaterial({color:priority?0xff4d6d:0xffb547,transparent:true,opacity:.8}));ring.rotation.x=Math.PI/2;g.add(ring);g.position.set(p.position_m[0],p.position_m[2]??heightAt(p.position_m[0],p.position_m[1]),p.position_m[1]);g.userData.priority=priority;world.add(g);poiEntities.set(p.id,g);return g;}
function updateMissionStory(t,events){const phase=document.querySelector('#mission-phase'), objective=document.querySelector('#mission-objective'), eventList=document.querySelector('#mission-events');const surveyed=t.pois.filter(p=>p.status==='SURVEYED').length;const emergency=events.some(e=>e.event_type==='EMERGENCY_POI');const outage=events.some(e=>e.event_type==='LINK_OUTAGE');const failure=events.some(e=>e.event_type==='UAV_FAILURE');const recovering=t.uavs.some(u=>u.role==='RELAY'||u.role==='RECOVER');if(failure){phase.textContent='Recovering from UAV failure';objective.textContent='The remaining swarm is rebuilding routes and redistributing the lost aircraft task.';}else if(outage){phase.textContent='Rebuilding the communication network';objective.textContent='The GCS link is degraded; relay UAVs are moving to restore multi-hop connectivity.';}else if(emergency){phase.textContent='Responding to emergency PoI';objective.textContent='A new high-priority disaster location has been inserted and is being assigned.';}else if(recovering){phase.textContent='Maintaining BVLOS connectivity';objective.textContent='Relay and recovery UAVs are preserving a route from survey aircraft back to the GCS.';}else if(surveyed<t.pois.length){phase.textContent='Surveying disaster locations';objective.textContent=`The swarm has surveyed ${surveyed}/${t.pois.length} PoIs while collecting telemetry and imagery metadata.`;}else{phase.textContent='Mission complete';objective.textContent='All assigned disaster locations are surveyed and the swarm is connected to the GCS.';}eventList.innerHTML=events.slice(-4).map(e=>`<div>• ${e.event_type||'EVENT'}${e.actor_id?` · ${e.actor_id}`:''}</div>`).join('');}
function updateTaskLines(t){taskLayer.clear();const pois=Object.fromEntries(t.pois.map(p=>[p.id,p]));for(const u of t.uavs){if(!u.task_id||u.role!=='SURVEY'||!pois[u.task_id])continue;const p=pois[u.task_id];const groundZ=p.position_m[2]??heightAt(p.position_m[0],p.position_m[1]);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(u.position_m[0],u.position_m[2],u.position_m[1]),new THREE.Vector3(p.position_m[0],groundZ+5,p.position_m[1])]),new THREE.LineDashedMaterial({color:roleColor.SURVEY,transparent:true,opacity:.85,dashSize:4,gapSize:2}));line.computeLineDistances();taskLayer.add(line);}}
function updateFootprints(t){for(const [id,ring] of footprintEntities){ring.visible=false;}for(const u of t.uavs){const radius=Number(u.survey_footprint_radius_m||0);if(!u.survey_capture_active||radius<=0)continue;let ring=footprintEntities.get(u.id);if(!ring){const points=[];for(let i=0;i<48;i++){const a=i/48*Math.PI*2;points.push(new THREE.Vector3(Math.cos(a),0,Math.sin(a)));}ring=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x39d98a,transparent:true,opacity:.8}));world.add(ring);footprintEntities.set(u.id,ring);}ring.visible=true;ring.position.set(u.position_m[0],u.position_m[2]-.8,u.position_m[1]);ring.scale.set(radius,1,radius);}}
function updateRouteLinks(t){const byId=Object.fromEntries(t.uavs.map(u=>[u.id,u]));const position=id=>id==='GCS'?[40,45,40]:byId[id]?.position_m;const wanted=new Map();for(const u of t.uavs){const route=u.route_to_gcs||[];for(let i=0;i<route.length-1;i++){const a=route[i],b=route[i+1];const key=[a,b].sort().join('|');if(!wanted.has(key))wanted.set(key,[a,b]);}}for(const [key,line] of linkLayer.userData.lines||[]){if(!wanted.has(key)){line.geometry.dispose();line.material.dispose();linkLayer.remove(line);linkLayer.userData.lines.delete(key);}}if(!linkLayer.userData.lines)linkLayer.userData.lines=new Map();for(const [key,[aId,bId]] of wanted){const a=position(aId),b=position(bId);if(!a||!b)continue;let line=linkLayer.userData.lines.get(key);if(!line){line=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:bId==='GCS'?0x39d98a:0x45aaf2,transparent:true,opacity:.42}));linkLayer.add(line);linkLayer.userData.lines.set(key,line);}line.geometry.dispose();line.geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(a[0],a[2],a[1]),new THREE.Vector3(b[0],b[2],b[1])]);}}
function render(){if(!replay?.ticks?.length)return; const t=replay.ticks[frame]; for(const p of t.pois){const g=poiEntities.get(p.id)||poiMarker(p);g.visible=true;g.children[0].material.opacity=p.status==='SURVEYED'?.35:1;g.children[1].material.opacity=p.status==='SURVEYED'?.25:.8;} for(const u of t.uavs){const g=entities.get(u.id)||drone(u.id); const target=new THREE.Vector3(u.position_m[0],u.position_m[2],u.position_m[1]); g.position.lerp(target,.8); const attitude=u.attitude_rpy_rad||[0,0,Math.atan2(u.velocity_mps[1],u.velocity_mps[0])];g.rotation.set(-attitude[1],attitude[2],attitude[0]); const thrust=(u.motor_thrust_n||[]).reduce((a,b)=>a+b,0)/Math.max(1,(u.motor_thrust_n||[]).length);g.userData.rotors?.forEach((r,i)=>{r.rotation.y+=.18+thrust*.004*(i%2?-1:1);});g.traverse(x=>{if(x.material&&!x.isMesh?.userData)x.material.color.setHex(x===g.userData.ledL?0x39d98a:x===g.userData.ledR?0xff4d5d:0x303944);}); const old=trails.get(u.id).geometry.getAttribute('position'), pts=[];if(old)for(let i=0;i<old.count;i++)pts.push(new THREE.Vector3().fromBufferAttribute(old,i));pts.push(g.position.clone());const trail=trails.get(u.id);trail.geometry.dispose();trail.geometry=new THREE.BufferGeometry().setFromPoints(pts.slice(-quality.trail));trail.material.color.setHex(roleColor[u.role]||0xaab4c3);}
 updateTaskLines(t); updateFootprints(t);
 updateRouteLinks(t);
 const events=(replay.events||[]).filter(e=>e.tick===t.tick);const banner=document.querySelector('#event-banner');const alertLabels=[...new Set(events.map(e=>`${e.event_type||'EVENT'}${e.actor_id?` · ${e.actor_id}`:''}`))];banner.innerHTML=alertLabels.slice(-4).map(label=>`<span>${label}</span>`).join('');banner.dataset.count=String(alertLabels.length);banner.style.opacity=events.length?'1':'0';updateMissionStory(t,events); const finalMetrics=replay.summary?.payload||replay.summary||{}; const metric=(key,dash='—')=>finalMetrics[key]===null||finalMetrics[key]===undefined?dash:(typeof finalMetrics[key]==='number'?finalMetrics[key].toFixed(2):finalMetrics[key]);const mapped=(t.survey_coverage_fraction||0)*100; telemetry.innerHTML=`<h2>MISSION STATUS · ${t.time_s.toFixed(1)} s</h2><p>Surveyed: ${t.pois.filter(p=>p.status==='SURVEYED').length}/${t.pois.length}<br>Mapped area: ${mapped.toFixed(1)}%<br>Connected: ${t.uavs.filter(u=>u.gcs_reachable&&!u.failed).length}/${t.uavs.length}<br>Packets: ${(t.packets||[]).filter(p=>p.delivered).length}/${(t.packets||[]).length}</p><hr><b>RUN METRICS</b><br>Completion: ${metric('mission_completion_rate')}<br>Connectivity: ${metric('connectivity_availability')}<br>Delivery: ${metric('packet_delivery_ratio')}<br>Latency: ${metric('mean_latency_ms')} ms<br>Recovery: ${metric('recovery_time_s_mean')} s<br>Collisions: ${metric('actual_collision_count','0')}<br>Battery violations: ${metric('battery_violations','0')}<br>Geofence violations: ${metric('geofence_violations','0')}<hr><b>UAV ROLES</b><br>${t.uavs.map(u=>`<span style="color:#${(roleColor[u.role]||0xaab4c3).toString(16).padStart(6,'0')}">● ${u.id}</span> ${u.role}${u.task_id?` → ${u.task_id}`:''} · ${u.battery_pct.toFixed(0)}%`).join('<br>')}`; document.querySelector('#seek').value=frame; }
function readReplayFile(file){return file.stream().pipeThrough(new TextDecoderStream()).getReader();}
async function parseJsonlStream(file){const reader=readReplayFile(file);let buffer='',result;const ticks=[],events=[];let manifest={},summary={};while(!(result=await reader.read()).done){buffer+=result.value;const lines=buffer.split(/\r?\n/);buffer=lines.pop();for(const line of lines){if(!line.trim())continue;const record=JSON.parse(line);if(record.record_type==='tick')ticks.push(record);else if(record.record_type==='event')events.push(record);else if(record.record_type==='manifest')manifest=record;else if(record.record_type==='summary')summary=record;}}if(buffer.trim()){const record=JSON.parse(buffer);if(record.record_type==='tick')ticks.push(record);else if(record.record_type==='event')events.push(record);else if(record.record_type==='manifest')manifest=record;else if(record.record_type==='summary')summary=record;}return {ticks,events,manifest,summary};}
document.querySelector('#file').onchange=async e=>{const f=e.target.files[0]; if(!f)return; replay=f.name.toLowerCase().endsWith('.jsonl')?await parseJsonlStream(f):parse(await f.text()); document.querySelector('#seek').max=replay.ticks.length-1; frame=0; render();};
document.querySelector('#quality').onchange=e=>{setQuality(e.target.value);};
document.querySelector('#speed').onchange=e=>{playbackSpeed=Number(e.target.value);};
document.querySelector('#play').onclick=()=>{playing=!playing; document.querySelector('#play').textContent=playing?'❚❚ Pause':'▶ Play';};
document.querySelector('#seek').oninput=e=>{frame=+e.target.value;render();};
document.querySelector('#camera').onclick=()=>{camera.position.set(420,360,360);controls.target.set(250,25,250);controls.update();};
// Presentation layer kept outside the authoritative renderer: it adds visual
// cues without changing replay state or inventing motion.
const authoritativeRender = render;
function updateFlightCues(t) {
  let readout = document.querySelector('#flight-readout');
  if (!readout) { readout = document.createElement('div'); readout.id = 'flight-readout'; document.body.appendChild(readout); }
  const airborne = t.uavs.filter(u => !u.failed && Number(u.position_m[2]) > 5).length;
  const backbone = t.uavs.filter(u => u.role === 'BACKBONE').length;
  readout.textContent = `AIRBORNE ${airborne}/${t.uavs.length}  •  ALTITUDE ${Math.max(...t.uavs.map(u => Number(u.position_m[2]) || 0)).toFixed(0)} m  •  BACKBONE ${backbone}`;
  for (const u of t.uavs) {
    const g = entities.get(u.id); if (!g) continue;
    g.scale.setScalar(2.2);
    const color = roleColor[u.role] || 0xaab4c3;
    let line = altitudeLines.get(u.id);
    if (!line) { line = new THREE.Line(new THREE.BufferGeometry(), new THREE.LineBasicMaterial({color, transparent:true, opacity:.42})); world.add(line); altitudeLines.set(u.id, line); }
    line.material.color.setHex(color); line.geometry.dispose(); line.geometry = new THREE.BufferGeometry().setFromPoints([
      new THREE.Vector3(u.position_m[0], heightAt(u.position_m[0], u.position_m[1]) + .5, u.position_m[1]),
      new THREE.Vector3(u.position_m[0], u.position_m[2], u.position_m[1])
    ]);
    let ring = roleRings.get(u.id);
    if (!ring) { ring = new THREE.Mesh(new THREE.TorusGeometry(6, .32, 8, 32), new THREE.MeshBasicMaterial({color, transparent:true, opacity:.72})); ring.rotation.x = Math.PI / 2; world.add(ring); roleRings.set(u.id, ring); }
    ring.material.color.setHex(color); ring.position.set(u.position_m[0], heightAt(u.position_m[0], u.position_m[1]) + 1.2, u.position_m[1]); ring.scale.setScalar(u.role === 'BACKBONE' ? 1.35 : 1);
  }
}
function configureReplayScene() {
  if (!replay?.manifest?.payload) return;
  const manifest = replay.manifest.payload;
  sceneArena = Number(manifest.arena_m || 1000);
  sceneGcs = (manifest.gcs_position_m || [-75, sceneArena / 2, 20]).slice();
  controls.target.set(sceneArena / 2, 35, sceneArena / 2);
  camera.position.set(sceneArena * .72, sceneArena * .58, sceneArena * .72);
  controls.maxDistance = sceneArena * 1.8;
  if (!gcsMarker) { gcsMarker = new THREE.Mesh(new THREE.CylinderGeometry(12, 15, 5, 24), new THREE.MeshStandardMaterial({color:0x45aaf2, emissive:0x062b46})); world.add(gcsMarker); }
  gcsMarker.position.set(sceneGcs[0], sceneGcs[2] || heightAt(sceneGcs[0], sceneGcs[1]) + 20, sceneGcs[1]);
  document.body.dataset.arena = String(sceneArena);
}
const originalFileChange = document.querySelector('#file').onchange;
document.querySelector('#file').onchange = async event => { await originalFileChange(event); configureReplayScene(); if (replay?.ticks?.length) { const t = replay.ticks[frame]; authoritativeRender(); updateFlightCues(t); } };
heightAt = function(x, z) { if (!terrainHeightmap) return 0; const grid = terrainHeightmap.grid, fx = Math.max(0, Math.min(grid - 1, x / sceneArena * (grid - 1))), fz = Math.max(0, Math.min(grid - 1, z / sceneArena * (grid - 1))), x0 = Math.floor(fx), z0 = Math.floor(fz), x1 = Math.min(x0 + 1, grid - 1), z1 = Math.min(z0 + 1, grid - 1), tx = fx - x0, tz = fz - z0, e = terrainHeightmap.elevation_m; return (1 - tz) * ((1 - tx) * e[z0][x0] + tx * e[z0][x1]) + tz * ((1 - tx) * e[z1][x0] + tx * e[z1][x1]); };
const baseRender = render;
updateRouteLinks = function(t) {
  const byId = Object.fromEntries(t.uavs.map(u => [u.id, u]));
  const position = id => id === 'GCS' ? [sceneGcs[0], sceneGcs[2] || 45, sceneGcs[1]] : byId[id]?.position_m;
  const wanted = new Map();
  for (const u of t.uavs) { const route = u.route_to_gcs || []; for (let i = 0; i < route.length - 1; i++) { const a = route[i], b = route[i + 1], key = [a, b].sort().join('|'); if (!wanted.has(key)) wanted.set(key, [a, b]); } }
  if (!linkLayer.userData.lines) linkLayer.userData.lines = new Map();
  for (const [key, line] of linkLayer.userData.lines) if (!wanted.has(key)) { line.geometry.dispose(); line.material.dispose(); linkLayer.remove(line); linkLayer.userData.lines.delete(key); }
  for (const [key, [aId, bId]] of wanted) { const a = position(aId), b = position(bId); if (!a || !b) continue; let line = linkLayer.userData.lines.get(key); if (!line) { line = new THREE.Line(new THREE.BufferGeometry(), new THREE.LineBasicMaterial({color:bId === 'GCS' ? 0x39d98a : 0x45aaf2, transparent:true, opacity:.58})); linkLayer.add(line); linkLayer.userData.lines.set(key, line); } line.geometry.dispose(); line.geometry = new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(a[0], a[2], a[1]), new THREE.Vector3(b[0], b[2], b[1])]); }
};
render = function() { baseRender(); if (replay?.ticks?.length) { const significant = new Set(['UAV_FAILURE','LINK_OUTAGE','EMERGENCY_POI','RETURN_HOME','MISSION_RECALL','LANDED']); const currentEvents = (replay.events || []).filter(e => e.tick === replay.ticks[frame].tick && significant.has(e.event_type)); const banner = document.querySelector('#event-banner'); if (banner) { banner.style.opacity = currentEvents.length ? '1' : '0'; banner.innerHTML = currentEvents.map(e => `<span>${e.event_type}${e.actor_id ? ` · ${e.actor_id}` : ''}</span>`).join(''); } updateFlightCues(replay.ticks[frame]); } };
setQuality('auto'); loadScene(); function loop(){requestAnimationFrame(loop);renderFrame++;if(renderFrame%30===0)updateTerrainTiles();if(playing&&replay&&replay.ticks.length&&renderFrame%Math.max(1,Math.round(8/playbackSpeed))===0){frame=(frame+1)%replay.ticks.length;render();}controls.update();renderer.render(scene,camera);} loop(); addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
