import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import './style.css';

const viewport = document.querySelector('#viewport'), telemetry = document.querySelector('#telemetry');
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x9fc4d8); scene.fog = new THREE.Fog(0x9fc4d8, 420, 980);
const camera = new THREE.PerspectiveCamera(48, innerWidth / innerHeight, .1, 2000); camera.position.set(420, 360, 360);
const renderer = new THREE.WebGLRenderer({antialias: true, powerPreference: 'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio, 1.5)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; viewport.appendChild(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); controls.target.set(250, 0, 250); controls.enableDamping = true;
scene.add(new THREE.HemisphereLight(0xd9efff, 0x5d654f, 3.8)); scene.add(new THREE.AmbientLight(0x9bb0bd, 1.2)); const sun = new THREE.DirectionalLight(0xffe4bd, 2.5); sun.position.set(220, 520, 140); sun.castShadow = true; sun.shadow.mapSize.set(2048,2048); scene.add(sun);
const world = new THREE.Group(); scene.add(world); const entities = new Map(), trails = new Map(), poiEntities = new Map(); const linkLayer = new THREE.Group(); world.add(linkLayer); let replay = null, frame = 0, playing = false;
const roleColor = {SURVEY: 0x39d98a, RELAY: 0x45aaf2, RECOVER: 0xffb547, RETURN: 0xff6b6b, CHARGE: 0xc084fc, STANDBY: 0xaab4c3};
function terrain() { const n=100, geo=new THREE.PlaneGeometry(500,500,n,n); const pos=geo.attributes.position, colors=[]; const low=new THREE.Color(0x263f2b), grass=new THREE.Color(0x58764a), dry=new THREE.Color(0x9b8955), high=new THREE.Color(0x8d8b78); for(let i=0;i<pos.count;i++){const x=pos.getX(i)+250,z=pos.getY(i)+250; const broad=13*Math.sin(x/92)*Math.cos(z/115), ridge=6*Math.sin((x+z)/31)+3*Math.cos(z/19), river=-10*Math.exp(-((z-245-42*Math.sin(x/75))**2)/900); const h=8+broad+ridge+river;pos.setZ(i,h);const moisture=Math.max(0,1-Math.abs(z-245-42*Math.sin(x/75))/85);let c=h>22?high.clone():h>13?grass.clone():dry.clone();c.lerp(low,Math.max(0,(8-h)/18));c.lerp(new THREE.Color(0x315d46),moisture*.35);colors.push(c.r,c.g,c.b);} geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals(); const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.96,metalness:0})); mesh.name='procedural-terrain'; mesh.rotation.x=-Math.PI/2; mesh.receiveShadow=true; mesh.position.set(250,0,250); world.add(mesh); const river=new THREE.Mesh(new THREE.PlaneGeometry(500,18),new THREE.MeshStandardMaterial({color:0x3d7890,roughness:.18,metalness:.15,transparent:true,opacity:.8}));river.rotation.x=-Math.PI/2;river.rotation.z=-.08;river.position.set(250,1.8,250);world.add(river); for(let i=0;i<28;i++){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(2+(i%4),0),new THREE.MeshStandardMaterial({color:i%2?0x6a6a5d:0x4e514d,roughness:1}));rock.position.set(20+(i*71)%460,10+(i%3)*2,25+(i*113)%450);rock.scale.y=.6;rock.castShadow=true;world.add(rock);} }
function drone(id){ const g=new THREE.Group(); g.scale.setScalar(1.45); const body=new THREE.Mesh(new THREE.CylinderGeometry(2.8,2.3,1.5,12),new THREE.MeshStandardMaterial({color:0x303944,metalness:.7,roughness:.3})); body.castShadow=true; g.add(body); const payload=new THREE.Mesh(new THREE.BoxGeometry(2.4,1.3,2.2),new THREE.MeshStandardMaterial({color:0x171d25,metalness:.4,roughness:.4}));payload.position.y=-1.2;g.add(payload); const gimbal=new THREE.Mesh(new THREE.SphereGeometry(.8,12,8),new THREE.MeshStandardMaterial({color:0x101820,metalness:.8,roughness:.2}));gimbal.position.set(0,-2.0,0);g.add(gimbal); const legs=new THREE.Mesh(new THREE.BoxGeometry(7,.22,1.8),new THREE.MeshStandardMaterial({color:0x202832,metalness:.5}));legs.position.y=-1.5;g.add(legs); const rotors=[]; for(let i=0;i<6;i++){const a=i*Math.PI/3,x=Math.cos(a)*5.0,z=Math.sin(a)*5.0;const arm=new THREE.Mesh(new THREE.BoxGeometry(5.2,.32,.32),new THREE.MeshStandardMaterial({color:0x202832,metalness:.6}));arm.position.set(x/2,0,z/2);arm.rotation.y=-a;g.add(arm);const motor=new THREE.Mesh(new THREE.CylinderGeometry(.65,.65,.7,12),new THREE.MeshStandardMaterial({color:0x171d25,metalness:.8}));motor.position.set(x,0,z);g.add(motor);const rotor=new THREE.Mesh(new THREE.CylinderGeometry(1.7,.08,.08,24),new THREE.MeshStandardMaterial({color:0xb9d5e8,transparent:true,opacity:.38}));rotor.position.set(x,.45,z);g.add(rotor);rotors.push(rotor);} const ledL=new THREE.PointLight(0x39d98a,1.8,14),ledR=new THREE.PointLight(0xff4d5d,1.8,14);ledL.position.set(-2,.2,0);ledR.position.set(2,.2,0);g.add(ledL,ledR);g.userData={id,rotors,ledL,ledR}; world.add(g); entities.set(id,g); const line=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xaab4c3,transparent:true,opacity:.6})); world.add(line); trails.set(id,line); return g; }
function obstacle(o){const [x,y,z]=o.center_m,[sx,sy,sz]=o.size_m; const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sz,sy),new THREE.MeshStandardMaterial({color:o.kind==='rubble'?0x766657:o.kind==='tower'?0x6c7f8c:0x8a8175,roughness:1})); m.position.set(x,z/2,y); m.castShadow=true; world.add(m);}
function sceneDetails(){
  const roadMat=new THREE.MeshStandardMaterial({color:0x252b2d,roughness:1});
  for(const [x,z,rot] of [[250,250,0],[250,120,Math.PI/2],[120,350,0]]){const road=new THREE.Mesh(new THREE.PlaneGeometry(500,7),roadMat);road.rotation.x=-Math.PI/2;road.rotation.z=rot;road.position.set(x,.4,z);world.add(road);}
  const trunk=new THREE.CylinderGeometry(.8,.55,8,6), crown=new THREE.ConeGeometry(4,10,7);
  for(let i=0;i<34;i++){const x=18+(i*83)%465,z=18+(i*137)%465;if(x>180&&x<285&&z>220&&z<305)continue;const tree=new THREE.Group();const t=new THREE.Mesh(trunk,new THREE.MeshStandardMaterial({color:0x5a3927}));t.position.y=4;const c=new THREE.Mesh(crown,new THREE.MeshStandardMaterial({color:i%3?0x2e633f:0x3d7d4a}));c.position.y=11;tree.add(t,c);tree.position.set(x,0,z);tree.scale.setScalar(.7+(i%4)*.12);tree.traverse(n=>n.castShadow=true);world.add(tree);}
}
function loadScene(){terrain(); sceneDetails(); fetch('/scene/obstacles.json').then(r=>r.json()).then(d=>d.obstacles.forEach(obstacle)).catch(()=>{}); fetch('/scene/scene_manifest.json').then(r=>r.json()).then(m=>{if(m.terrain?.gltf_url){new GLTFLoader().load(m.terrain.gltf_url,g=>{const real=g.scene;real.name='real-terrain';real.traverse(x=>{if(x.isMesh){x.castShadow=false;x.receiveShadow=true;if(x.material){x.material.side=THREE.DoubleSide;x.material.roughness=.94;}if(m.terrain.albedo_url){new THREE.TextureLoader().load(m.terrain.albedo_url,tex=>{tex.colorSpace=THREE.SRGBColorSpace;x.material.map=tex;x.material.needsUpdate=true;});}}});world.add(real);const fallback=world.getObjectByName('procedural-terrain');if(fallback)fallback.visible=false;document.title=`UAV-X · ${m.scene_id||'real scene'}`;},undefined,()=>{});} if(m.drone_model?.gltf_url){new GLTFLoader().load(m.drone_model.gltf_url,g=>{window.droneTemplate=g.scene;});}}).catch(()=>{}); const gcs=new THREE.Mesh(new THREE.CylinderGeometry(8,10,3,24),new THREE.MeshStandardMaterial({color:0x45aaf2})); gcs.position.set(40,45,40); world.add(gcs);}
function parse(text){const lines=text.trim().split(/\r?\n/); if(lines.length && lines[0].startsWith('{') && !text.trim().startsWith('{"schema_version":"uav-x-log')){try{return JSON.parse(text);}catch{}} const records=lines.map(x=>JSON.parse(x)); return {ticks:records.filter(x=>x.record_type==='tick'),events:records.filter(x=>x.record_type==='event'),manifest:records.find(x=>x.record_type==='manifest')||{}};}
function poiMarker(p){const g=new THREE.Group();const pin=new THREE.Mesh(new THREE.ConeGeometry(2.5,7,6),new THREE.MeshStandardMaterial({color:0xffb547,emissive:0x5a2d00}));pin.position.y=3;g.add(pin);const ring=new THREE.Mesh(new THREE.TorusGeometry(5,.35,8,24),new THREE.MeshBasicMaterial({color:0xffb547,transparent:true,opacity:.7}));ring.rotation.x=Math.PI/2;g.add(ring);g.position.set(p.position_m[0],p.position_m[2],p.position_m[1]);world.add(g);poiEntities.set(p.id,g);return g;}
function render(){if(!replay?.ticks?.length)return; const t=replay.ticks[frame]; for(const p of t.pois){const g=poiEntities.get(p.id)||poiMarker(p);g.visible=p.status!=='SURVEYED';} for(const u of t.uavs){const g=entities.get(u.id)||drone(u.id); const target=new THREE.Vector3(u.position_m[0],u.position_m[2],u.position_m[1]); g.position.lerp(target,.8); const attitude=u.attitude_rpy_rad||[0,0,Math.atan2(u.velocity_mps[1],u.velocity_mps[0])];g.rotation.set(-attitude[1],attitude[2],attitude[0]); const thrust=(u.motor_thrust_n||[]).reduce((a,b)=>a+b,0)/Math.max(1,(u.motor_thrust_n||[]).length);g.userData.rotors?.forEach((r,i)=>{r.rotation.y+=.18+thrust*.004*(i%2?-1:1);});g.traverse(x=>{if(x.material&&!x.isMesh?.userData)x.material.color.setHex(x===g.userData.ledL?0x39d98a:x===g.userData.ledR?0xff4d5d:0x303944);}); const old=trails.get(u.id).geometry.getAttribute('position'), pts=[];if(old)for(let i=0;i<old.count;i++)pts.push(new THREE.Vector3().fromBufferAttribute(old,i));pts.push(g.position.clone());const trail=trails.get(u.id);trail.geometry.dispose();trail.geometry=new THREE.BufferGeometry().setFromPoints(pts.slice(-50));trail.material.color.setHex(roleColor[u.role]||0xaab4c3);}
 linkLayer.clear();const byId=Object.fromEntries(t.uavs.map(u=>[u.id,u]));for(const l of (t.links||[]).filter(x=>x.available&&x.source_id!=='GCS'&&x.target_id!=='GCS')){const a=byId[l.source_id],b=byId[l.target_id];if(!a||!b)continue;const points=[new THREE.Vector3(a.position_m[0],a.position_m[2],a.position_m[1]),new THREE.Vector3(b.position_m[0],b.position_m[2],b.position_m[1])];linkLayer.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x45aaf2,transparent:true,opacity:.3})));}
 const events=(replay.events||[]).filter(e=>e.tick===t.tick);const banner=document.querySelector('#event-banner');banner.textContent=events.map(e=>`${e.payload?.event_type||'EVENT'} · ${e.payload?.actor_id||''}`).join('   ');banner.style.opacity=events.length?'1':'0';telemetry.innerHTML=`<h2>MISSION STATUS · ${t.time_s.toFixed(1)} s</h2><p>Surveyed: ${t.pois.filter(p=>p.status==='SURVEYED').length}/${t.pois.length}<br>Connected: ${t.uavs.filter(u=>u.gcs_reachable&&!u.failed).length}/${t.uavs.length}<br>Packets: ${(t.packets||[]).filter(p=>p.delivered).length}/${(t.packets||[]).length}</p><hr><b>UAV ROLES</b><br>${t.uavs.map(u=>`<span style="color:#${(roleColor[u.role]||0xaab4c3).toString(16).padStart(6,'0')}">● ${u.id}</span> ${u.role} · ${u.battery_pct.toFixed(0)}%`).join('<br>')}`; document.querySelector('#seek').value=frame; }
document.querySelector('#file').onchange=e=>{const f=e.target.files[0]; if(!f)return; f.text().then(x=>{replay=parse(x); document.querySelector('#seek').max=replay.ticks.length-1; frame=0; render();});}; document.querySelector('#play').onclick=()=>{playing=!playing; document.querySelector('#play').textContent=playing?'❚❚ Pause':'▶ Play';}; document.querySelector('#seek').oninput=e=>{frame=+e.target.value;render();};
loadScene(); function loop(){requestAnimationFrame(loop);if(playing&&replay&&replay.ticks.length){frame=(frame+1)%replay.ticks.length;render();}controls.update();renderer.render(scene,camera);} loop(); addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
